[versions]
activityCompose = "1.12.2"
agp = "8.13.2"
colorpicker = "1.1.3"
composeBom = "2025.12.01"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
firebaseBom = "34.7.0"
firebaseCrashlytics = "20.0.3"
firebasePerf = "22.0.4"
intro-showcase = "2.0.2"
junit = "4.13.2"
junitVersion = "1.3.0"
koinBom = "4.1.1"
kotlin = "2.3.0"
kotlin-test = "1.10.2"
lifecycleRuntimeKtx = "2.10.0"
mockk = "1.14.7"
navigationCompose = "2.9.6"
room = "2.8.4"
timber = "5.0.1"
version-catalog-update = "1.0.1"
kotlin-ksp = "2.3.4"
google-services = "4.4.4"
firebase-crashlytics-plugin = "3.0.6"
firebase-perf-plugin = "2.0.2"
materialIconsCore = "1.7.8"
material3 = "1.4.0"
truth = "1.4.5"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-colorpicker = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpicker" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebasePerf" }
intro-showcase = { module = "com.canopas.intro-showcase-view:introshowcaseview", version.ref = "intro-showcase" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-test" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
firebase-crashlytics-plugin = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
firebase-perf-plugin = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf-plugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
